version: "3"

services:
  web:
    build: .
    ports:
      - "8001:8000"
    # volumes:
    #   - .:/app
    depends_on:
      - db
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ticket_db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3310:3306"
